package:
  name: arsc
  version: "0.2.1"

source:
  git_url: https://github.com/stsnsn/ARSC.git
  git_tag: main

build:
  number: 0
  script: python -m pip install .

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - biopython >=1.79

test:
  commands:
    - ARSC -h

about:
  home: https://github.com/stsnsn/ARSC
  license: GPL-2.0
  summary: "Compute ARSCs from protein fasta files"